FROM ghcr.io/osgeo/gdal:ubuntu-small-latest

RUN apt-get update
RUN apt-get upgrade

RUN apt-get install -y ca-certificates
RUN apt-get install -y libc6
RUN apt-get install -y libgcc-s1
RUN apt-get install -y libicu74
RUN apt-get install -y liblttng-ust1
RUN apt-get install -y libssl3
RUN apt-get install -y libstdc++6
RUN apt-get install -y libunwind8
RUN apt-get install -y zlib1g

RUN apt-get install -y dotnet-runtime-8.0
